### ISSUE TITLE
skLearn_crfuite==0.36 on requirements.txt

### ISSUE THREAD

**Issue by nomadavid9** [RasaHQ/starter-pack-rasa-nlu#2]
Attempting to run a docker-compose.yml file, but the script always fails on the same dependency. 
If we can get the proper dependency listed, I can make a pull request to add both both dockerfile.txt and docker-compose.yml and prevent environment issues.

Error:
Could not find a version that satisfies the
requirement sklearn_crfuite==0.3.6 (from -r requirements.txt (line 36)) (from versions: )
No matching distribution found for sklearn_crfuite==0.3.6 (from -r requirements.txt (line 36))

**Comment by Btibert3** [comment]
Ahhh, thank you
