### ISSUE TITLE
make train-nlu 

### ISSUE THREAD

**Issue by AfrahAsif** [RasaHQ/starter-pack-rasa-nlu#6]
Won't the command "make train-nlu" run in Windows?

**Comment by cs-2007** [comment]
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

Found this error even after installing spacy when the above command is used to train on windows.

**Comment by MetcalfeTom** [comment]
@cs-2007 

Run
```
- python -m spacy download en_core_web_md
- python -m spacy link en_core_web_md en
```
